{{- include "helx-common.secret.resources.v1" (dict
  "root" .
  "defaultName" (include "appstore-sockets.fullname" .)
  "mode" .Values.secret.mode
  "errorValuePath" "secret"
  "existingSecret" .Values.secret.existingSecret
  "values" .Values.secret.values
  "externalSecret" .Values.secret.externalSecret
  "externalSecretName" (include "appstore-sockets.fullname" .)
  "requiredKeys" (list "PUBLISHER_SECRET")
) -}}
