{{- $mode := include "helx-common.secret.mode.v1" (dict
  "mode" .Values.secret.mode
  "existingSecret" .Values.secret.existingSecret
  "externalSecret" .Values.secret.externalSecret
  "secretValueBlockPath" "secret"
) -}}
{{- $secretValues := deepCopy (default (dict) .Values.secret.values) -}}
{{- if and (eq $mode "values") (not (hasKey $secretValues "PUBLISHER_SECRET")) -}}
  {{- $_ := set $secretValues "PUBLISHER_SECRET" (randAlphaNum 50) -}}
{{- end -}}
{{- include "helx-common.secret.resources.v1" (dict
  "root" .
  "defaultName" (include "appstore-sockets.fullname" .)
  "mode" $mode
  "secretValueBlockPath" "secret"
  "existingSecret" .Values.secret.existingSecret
  "values" $secretValues
  "externalSecret" .Values.secret.externalSecret
  "externalSecretName" (include "appstore-sockets.fullname" .)
  "requiredKeys" (list "PUBLISHER_SECRET")
) -}}
