{{- $patcher := index .Values "imagepullsecret-patcher" -}}
{{- if $patcher.enabled -}}
{{- include "helx-common.secret.resources.v1" (dict
  "root" .
  "defaultName" "image-pull-secret"
  "existingSecret" .Values.secret.existingSecret
  "values" .Values.secret.values
  "externalSecret" .Values.secret.externalSecret
  "externalSecretName" (include "image-utils.imagepullsecret-patcher.fullname" .)
  "requiredKeys" (list ".dockerconfigjson")
  "type" "kubernetes.io/dockerconfigjson"
) -}}
{{- end -}}
