{{- if .Values.basicAuth.enabled }}
{{- include "helx-common.secret.resources.v1" (dict
  "root" .
  "defaultName" (include "resty.basicAuthManagedSecretName" .)
  "existingSecret" .Values.secret.existingSecret
  "values" .Values.secret.values
  "externalSecret" .Values.secret.externalSecret
  "externalSecretName" (include "resty.fullname" .)
  "requiredKeys" (list "auth")
) -}}
{{- end }}
