// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/hook": {
            "post": {
                "description": "Receives an LDAP entry, applies transformation logic, and returns the transformed entry along with derived search specifications.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Process LDAP hook payload",
                "parameters": [
                    {
                        "description": "LDAP Entry Payload",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/main.HookRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.HookResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.DerivedSpec": {
            "type": "object",
            "properties": {
                "baseDN": {
                    "type": "string"
                },
                "filter": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "refresh": {
                    "type": "integer"
                }
            }
        },
        "main.HookRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "object",
                    "additionalProperties": true
                },
                "dn": {
                    "type": "string"
                }
            }
        },
        "main.HookResponse": {
            "type": "object",
            "properties": {
                "derived": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.DerivedSpec"
                    }
                },
                "transformed": {
                    "$ref": "#/definitions/main.Transformed"
                }
            }
        },
        "main.Transformed": {
            "type": "object",
            "properties": {
                "content": {
                    "$ref": "#/definitions/main.TransformedContent"
                },
                "dn": {
                    "type": "string"
                }
            }
        },
        "main.TransformedContent": {
            "type": "object",
            "properties": {
                "cn": {
                    "type": "string"
                },
                "member": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "objectClass": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:5001",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "LDAP Sync Hook Service",
	Description:      "This service transforms LDAP entries and derives additional search specifications.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
