definitions:
  main.Derived:
    properties:
      baseDN:
        example: ou=people,dc=unc,dc=edu
        type: string
      filter:
        example: (|(pid=713272486)(pid=709909262)... )
        type: string
      id:
        example: ordrd-members
        type: string
      refresh:
        example: 10
        type: integer
    type: object
  main.ErrorResponse:
    properties:
      message:
        type: string
    type: object
  main.HookRequest:
    properties:
      content:
        additionalProperties: true
        type: object
      dn:
        example: cn=unc:app:renci:ordrd-example,ou=Groups,dc=unc,dc=edu
        type: string
    type: object
  main.HookResponse:
    properties:
      derived:
        items:
          $ref: '#/definitions/main.Derived'
        type: array
      reset:
        type: boolean
      transformed: {}
    type: object
info:
  contact: {}
paths:
  /hook:
    post:
      consumes:
      - application/json
      description: Accepts LDAP payload and returns transformed data.
      parameters:
      - description: LDAP Payload
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.HookRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.HookResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.ErrorResponse'
      summary: Process LDAP hook payload
      tags:
      - hook
swagger: "2.0"
