apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "appstore-prepuller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "appstore-prepuller.labels" . | nindent 4 }}
