appstore:
  DEBUG: "true"
  logLevel: DEBUG
  saml:
    ASSERTION_URL: https://helx-test.apps.renci.org
    ENTITY_ID: https://helx-test.apps.renci.org/saml2_auth/acs/
  tycho:
    externalAppRegistryBranch: ordrd-staging
appstore-prepuller:
  appRegistry:
    branch: ordrd-staging
    brand: ordrd
ldap-sync:
  config:
    hooks:
      - args:
          - --baseGid=1025
          - --baseGroup=helx-users
        image:
          repository: containers.renci.org/helxplatform/unc-group-x
          tag: sterling-ldapfix-1
        name: unc-group-x
        url: http://localhost:5001/hook
resty:
  SSL:
    nginxTLSSecret: helx-test-apps-renci-org-tls
  service:
    serverName: helx-test.apps.renci.org
ui:
  config:
    appstore_asset_base_url: https:\/\/raw.githubusercontent.com\/helxplatform\/appstore
    appstore_asset_branch: develop
    brand_description:
      html: |
        <div style="display:flex;flex-direction:column;align-items:center;"> <h4 style="max-width:450px;">
          A platform for analysis of clinical data records
        </h4> <p style="max-width:450px;">
          The de-identified OMOP Research Data Repository, ORDR(D) for short,
          is a joint effort between NC TraCS and RENCI focused on building
          new health research-focused data warehousing at UNC.
        </p> </div>
    brand_name: ordrd
    default_space: workspaces
    hidden_result_tabs: cdes
    login_title: RENCI HeLx Test Workspaces
    meta:
      title: RENCI HeLx Test
    search:
      enabled: "false"
      url: ""
    support:
      faqs_url: ""
      help_portal_url: https:\/\/renci.atlassian.net\/servicedesk\/customer\/portal\/9
      user_guide_url: https:\/\/renci.atlassian.net\/wiki\/x\/BID7P
    workspaces:
      enabled: "true"
user-mutator:
  config:
    features:
      ldap:
        host: openldap
        port: 389
        username: "cn=admin,dc=example,dc=org"
        user_base_dn: "ou=users,dc=example,dc=org"
        group_base_dn: "ou=groups,dc=example,dc=org"
