# Generated by Django 4.2 on 2024-10-28 18:45

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20200430_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='IrodAuthorizedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(max_length=254)),
                ('uid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='authorizeduser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='authorizeduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='authorizeduser',
            name='username',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.CreateModel(
            name='UserIdentityToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=core.models.generate_token, max_length=256, unique=True)),
                ('consumer_id', models.CharField(default=None, max_length=256, null=True)),
                ('expires', models.DateTimeField(default=core.models.user_token_expires)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
